application: cal-backend
version: 4
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /query/.*
  script: query.application

- url: /sync
  script: sync_service.application
  login: admin


